In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)

In [3]:
data

array([[-1.02728384, -1.11089997,  0.54581522],
       [ 0.27820905,  0.92275668,  1.61203702]])

In [4]:
data.shape
data.dtype

dtype('float64')

In [5]:
data.shape

(2, 3)

In [6]:
array = np.array(data)

In [7]:
array

array([[-1.02728384, -1.11089997,  0.54581522],
       [ 0.27820905,  0.92275668,  1.61203702]])

In [8]:
arr = np.array(data)

In [9]:
arr.ndim

2

In [10]:
np.zeors((3, 6))

AttributeError: module 'numpy' has no attribute 'zeors'

In [11]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.empty(2, 3, 4)

TypeError: data type not understood

In [13]:
np.empty((2, 3, 4))

array([[[5.19362736e-316, 7.75683064e-322, 0.00000000e+000,
         0.00000000e+000],
        [7.56599806e-307, 1.15998412e-028, 2.44171989e+232,
         8.00801729e+159],
        [3.35733962e-090, 5.88175940e-062, 8.54406004e-072,
         1.08725049e-095]],

       [[6.23127688e-038, 4.07356335e+223, 8.94213159e+130,
         1.57347469e-076],
        [3.24245676e-086, 6.52744652e-038, 6.38415296e-067,
         1.95360833e-109],
        [2.86752281e+161, 2.78225500e+296, 9.80058441e+252,
         1.23971686e+224]]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array

array([[-1.02728384, -1.11089997,  0.54581522],
       [ 0.27820905,  0.92275668,  1.61203702]])

In [16]:
arr2 = np.arange(10)

In [17]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr2.dtype

dtype('int32')

In [19]:
f_arr = arr2.astype(np.float64)

In [20]:
f_arr.dtype

dtype('float64')

In [21]:
num_str = np.array(['1.1', '-0.5'],dtype = np.string)

AttributeError: module 'numpy' has no attribute 'string'

In [22]:
num_str = np.array(['1.1', '-0.5'],dtype = np.string_)

In [23]:
num_str.astype(float)

array([ 1.1, -0.5])

In [24]:
version

NameError: name 'version' is not defined

In [25]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]])

In [26]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [28]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [29]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [30]:
arr2 = np.random.randn(2,5,2,3)

In [31]:
arr2

array([[[[ 0.48107866, -0.79314487, -1.47756067],
         [ 0.09407114,  0.2615705 , -1.44659285]],

        [[-1.60229666,  1.3599674 , -0.07119627],
         [ 0.03169446,  0.32066494,  0.26776223]],

        [[ 0.08649464,  0.44457653,  1.40189589],
         [-1.96431845, -0.77746754, -0.37083829]],

        [[-0.40378837,  0.07266952, -0.25222511],
         [ 0.77625823,  0.02534925, -1.28526196]],

        [[ 0.69611809, -0.06569523,  1.4077907 ],
         [-1.58147727, -1.10863526, -1.08760531]]],


       [[[ 1.00300101,  0.75029316, -0.93185606],
         [-0.22204537,  0.86730925,  1.34007467]],

        [[ 0.10894033, -0.21049678, -0.95646067],
         [-0.63064565,  1.99895588, -0.24735951]],

        [[ 0.90012604,  0.44380358,  0.67409196],
         [-0.01041596, -0.63800318,  0.88624467]],

        [[ 0.99996255,  0.27570834, -0.740041  ],
         [ 0.18361918, -0.2815601 , -1.16333551]],

        [[-0.42161651, -0.17182216, -3.0005917 ],
         [ 0.36821097, -0.5776

In [32]:
arr2 = np.random.randn(2,3)

In [33]:
arr2

array([[-1.0247694 , -1.45721434,  1.0075856 ],
       [-1.33587981, -0.34213749,  0.86132425]])

In [34]:
arr2>arr

array([[False, False, False],
       [False, False, False]])

In [35]:
arr = np.arange(10)

In [36]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[5]

5

In [38]:
arr[-1]

9

In [39]:
arr[5:8]

array([5, 6, 7])

In [40]:
arr[5:8] =12

In [41]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [42]:
arr_slice = arr[5:8]

In [43]:
arr_slice

array([12, 12, 12])

In [44]:
arr_slice[1
        ] = 123

In [45]:
arr

array([  0,   1,   2,   3,   4,  12, 123,  12,   8,   9])

In [46]:
arr_slice[:] = 64

In [47]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [48]:
arr2d = np.arr([1,2,3],[4,5,6])

AttributeError: module 'numpy' has no attribute 'arr'

In [49]:
arr2d = np.array([1,2,3],[4,5,6])

TypeError: data type not understood

In [50]:
arr2d = np.array([[1,2,3],[4,5,6]])

In [51]:
arr2d[1]

array([4, 5, 6])

In [52]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [53]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [54]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr2d[:,:1]

array([[1],
       [4]])

In [56]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe
                  '])

SyntaxError: EOL while scanning string literal (<ipython-input-56-ea6a9660717b>, line 1)

In [57]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [58]:
data = np.random.randn(7,4)

In [59]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [60]:
data

array([[ 0.57887332,  1.1911457 , -0.29896429,  0.0663505 ],
       [-1.72039698,  0.01454672,  0.5875587 ,  0.98367156],
       [ 0.10924411,  1.21728692, -0.39216469,  1.04377894],
       [-2.08494676, -0.78500999,  1.37891446, -0.82951649],
       [-0.39929426, -0.075954  ,  1.35878454,  0.38690174],
       [ 0.51233418,  0.72394054, -1.32106426,  0.27495943],
       [ 0.33440652,  0.36587923,  1.46230302, -0.63690515]])

In [63]:
names !='Bob'

array([False,  True,  True, False,  True,  True,  True])

In [62]:
data[ names =='Bob' ]

array([[ 0.57887332,  1.1911457 , -0.29896429,  0.0663505 ],
       [-2.08494676, -0.78500999,  1.37891446, -0.82951649]])

In [64]:
names !='Bob'

array([False,  True,  True, False,  True,  True,  True])

In [65]:
data[~(names =='Bob')]

array([[-1.72039698,  0.01454672,  0.5875587 ,  0.98367156],
       [ 0.10924411,  1.21728692, -0.39216469,  1.04377894],
       [-0.39929426, -0.075954  ,  1.35878454,  0.38690174],
       [ 0.51233418,  0.72394054, -1.32106426,  0.27495943],
       [ 0.33440652,  0.36587923,  1.46230302, -0.63690515]])

In [66]:
cond = names =='Bob'

In [67]:
cond

array([ True, False, False,  True, False, False, False])

In [68]:
data[~cond]

array([[-1.72039698,  0.01454672,  0.5875587 ,  0.98367156],
       [ 0.10924411,  1.21728692, -0.39216469,  1.04377894],
       [-0.39929426, -0.075954  ,  1.35878454,  0.38690174],
       [ 0.51233418,  0.72394054, -1.32106426,  0.27495943],
       [ 0.33440652,  0.36587923,  1.46230302, -0.63690515]])

In [69]:
mask = (names =='Bob')|(names =='Will')

In [70]:
mask

array([ True, False,  True,  True,  True, False, False])

In [71]:
data[mask]

array([[ 0.57887332,  1.1911457 , -0.29896429,  0.0663505 ],
       [ 0.10924411,  1.21728692, -0.39216469,  1.04377894],
       [-2.08494676, -0.78500999,  1.37891446, -0.82951649],
       [-0.39929426, -0.075954  ,  1.35878454,  0.38690174]])

In [72]:
data[mask,1] = 666

In [73]:
data[mask]

array([[ 5.78873318e-01,  6.66000000e+02, -2.98964294e-01,
         6.63505001e-02],
       [ 1.09244107e-01,  6.66000000e+02, -3.92164693e-01,
         1.04377894e+00],
       [-2.08494676e+00,  6.66000000e+02,  1.37891446e+00,
        -8.29516495e-01],
       [-3.99294259e-01,  6.66000000e+02,  1.35878454e+00,
         3.86901735e-01]])

In [74]:
data[mask,1] = 6

In [75]:
data[mask]

array([[ 0.57887332,  6.        , -0.29896429,  0.0663505 ],
       [ 0.10924411,  6.        , -0.39216469,  1.04377894],
       [-2.08494676,  6.        ,  1.37891446, -0.82951649],
       [-0.39929426,  6.        ,  1.35878454,  0.38690174]])

In [76]:
data

array([[ 0.57887332,  6.        , -0.29896429,  0.0663505 ],
       [-1.72039698,  0.01454672,  0.5875587 ,  0.98367156],
       [ 0.10924411,  6.        , -0.39216469,  1.04377894],
       [-2.08494676,  6.        ,  1.37891446, -0.82951649],
       [-0.39929426,  6.        ,  1.35878454,  0.38690174],
       [ 0.51233418,  0.72394054, -1.32106426,  0.27495943],
       [ 0.33440652,  0.36587923,  1.46230302, -0.63690515]])

In [77]:
data[data<0] =0 

In [78]:
data

array([[0.57887332, 6.        , 0.        , 0.0663505 ],
       [0.        , 0.01454672, 0.5875587 , 0.98367156],
       [0.10924411, 6.        , 0.        , 1.04377894],
       [0.        , 6.        , 1.37891446, 0.        ],
       [0.        , 6.        , 1.35878454, 0.38690174],
       [0.51233418, 0.72394054, 0.        , 0.27495943],
       [0.33440652, 0.36587923, 1.46230302, 0.        ]])

In [79]:
data[names !='Joe']=7

In [80]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.01454672, 0.5875587 , 0.98367156],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.51233418, 0.72394054, 0.        , 0.27495943],
       [0.33440652, 0.36587923, 1.46230302, 0.        ]])

In [81]:
arr = np.empty((8, 4))

In [82]:
arr

array([[ 9.38724727e-323,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  4.92089383e-321,  0.00000000e+000,
         0.00000000e+000],
       [ 8.02760759e-315, -3.59162350e-312,  9.88131292e-324,
         0.00000000e+000],
       [ 2.12199579e-314,  0.00000000e+000,  0.00000000e+000,
         4.94065646e-321],
       [ 8.48798316e-314, -3.58617289e-312,  3.86282537e-316,
        -3.59162350e-312],
       [ 8.39911598e-323,  2.27270197e-322,  3.85628197e-316,
         3.95252517e-323],
       [ 1.97626258e-323,  8.02560168e-315,  8.02559866e-315,
         8.02101541e-315],
       [ 8.02760759e-315, -3.59162350e-312,  1.08694442e-322,
         0.00000000e+000]])

In [83]:
for i in range(8):
    arr[i] = i

In [84]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [85]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [86]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [87]:
arrr = np.arange(32).reshape((8,4))

In [88]:
arrr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [89]:
arrr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [90]:
arrr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [91]:
arrr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [92]:
arrr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [93]:
arrr = np.random.randn(8,4)

In [94]:
arrr

array([[-1.46780326, -1.07778982, -3.44972393,  0.09324837],
       [-0.60308364, -0.13431554,  0.14282623,  1.07671988],
       [ 0.72423265,  0.40915291, -1.06168961, -1.19052857],
       [-1.43577121,  1.26391772,  0.97696954, -0.66335976],
       [ 1.10550967,  3.2117071 ,  0.74997946,  0.66605317],
       [-0.8395813 ,  1.21897405, -0.24092905,  0.04804228],
       [-1.41552574, -0.77395966,  0.62780371, -1.16496058],
       [ 0.34996767,  0.31131519, -0.16938937,  0.30037218]])

In [95]:
arrr.T

array([[-1.46780326, -0.60308364,  0.72423265, -1.43577121,  1.10550967,
        -0.8395813 , -1.41552574,  0.34996767],
       [-1.07778982, -0.13431554,  0.40915291,  1.26391772,  3.2117071 ,
         1.21897405, -0.77395966,  0.31131519],
       [-3.44972393,  0.14282623, -1.06168961,  0.97696954,  0.74997946,
        -0.24092905,  0.62780371, -0.16938937],
       [ 0.09324837,  1.07671988, -1.19052857, -0.66335976,  0.66605317,
         0.04804228, -1.16496058,  0.30037218]])

In [96]:
np.dot(arrr.T, arrr)

array([[ 9.15734709,  3.87626765,  2.88920078,  1.75413583],
       [ 3.87626765, 15.44145657,  6.07570914,  1.62221015],
       [ 2.88920078,  6.07570914, 15.04599509,  0.15369721],
       [ 1.75413583,  1.62221015,  0.15369721,  4.91871688]])

In [97]:
arr = np.arange(16).reshape((2,2,4))

In [98]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [99]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [100]:
arr = np.arange(16).reshape((2,2,4))

In [101]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [102]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [103]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [104]:
arr.T


array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [105]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [106]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [107]:
arr = np.arange(16).reshpe(4,4)

AttributeError: 'numpy.ndarray' object has no attribute 'reshpe'

In [108]:
arr = np.arange(16).reshape(4,4)

In [109]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:
arr.swapaxes(1,2)

ValueError: bad axis2 argument to swapaxes

In [111]:
arr = np.arange(16).reshape((2,2,4))

In [112]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [113]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [114]:
read to page 110

SyntaxError: invalid syntax (<ipython-input-114-e3e36b188bdc>, line 1)

In [115]:
print('read to page 110')

read to page 110
